services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    restart: always
    environment:
      PORT: ${PORT:-8083}
      DB_HOST: ${NOTIFICATION_DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-notification_db}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672/}
      SMTP_HOST: ${SMTP_HOST:-mailpit}
      SMTP_PORT: ${SMTP_PORT:-1025}
      SMTP_FROM: ${SMTP_FROM:-no-reply@company.com}
      AUTH_JWT_PUBLIC_KEY_PEM: ${AUTH_JWT_PUBLIC_KEY_PEM}

    ports:
      - "${PORT:-8083}:${PORT:-8083}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=microservice-network"
      - "traefik.http.routers.notification-service.rule=PathPrefix(`/api/notifications`)"
      - "traefik.http.routers.notification-service.entrypoints=web"
      - "traefik.http.services.notification-service.loadbalancer.server.port=8083"
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    external: true
