services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    restart: always
    environment:
      DB_HOST: ${NOTIFICATION_DB_HOST:-postgres}
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: notification_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_FROM: no-reply@company.com
      PORT: 8083
      AUTH_JWT_PUBLIC_KEY_PEM: ${AUTH_JWT_PUBLIC_KEY_PEM}

    ports:
      - "${PORT:-8083}:${PORT:-8083}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=microservice-network"
      - "traefik.http.routers.notification-service.rule=PathPrefix(`/api/notifications`)"
      - "traefik.http.routers.notification-service.entrypoints=web"
      - "traefik.http.services.notification-service.loadbalancer.server.port=8083"
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    external: true
