package repository

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/lib/pq"
	"notification-service/internal/infrastructure/postgres"
)

// InboxRepository provides idempotent event deduplication via the Inbox Pattern.
// Every incoming RabbitMQ message carries an event_id generated by the sender's outbox.
// By attempting to INSERT that event_id into a table with a PRIMARY KEY constraint,
// we detect duplicates in a single atomic DB operation — no SELECT needed.
type InboxRepository interface {
	// TryInsert attempts to record the event_id inside an open transaction.
	//
	// Returns (true, nil)  → Duplicate: this event_id was already processed. The caller
	//                        should roll back the transaction and ACK the message without
	//                        performing any business logic.
	//
	// Returns (false, nil) → First time: proceed with business logic inside the same TX,
	//                        then commit.
	//
	// Returns (false, err) → Unexpected DB error: caller should NACK and retry.
	TryInsert(ctx context.Context, tx *sql.Tx, eventID string) (isDuplicate bool, err error)
}

type postgresInboxRepository struct {
	client *postgres.Client
}

func NewInboxRepository(client *postgres.Client) InboxRepository {
	return &postgresInboxRepository{client: client}
}

func (r *postgresInboxRepository) TryInsert(ctx context.Context, tx *sql.Tx, eventID string) (bool, error) {
	const query = `INSERT INTO public.inbox (event_id) VALUES ($1);`
	_, err := tx.ExecContext(ctx, query, eventID)
	if err != nil {
		// PostgreSQL error code 23505 = unique_violation.
		// This means the event_id PRIMARY KEY already exists — the message is a duplicate.
		if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23505" {
			return true, nil // isDuplicate = true
		}
		return false, fmt.Errorf("failed to insert event_id into inbox: %w", err)
	}
	return false, nil // isDuplicate = false, safe to process
}
