services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      PORT: 8081
      AUTH_JWT_PUBLIC_KEY_PEM: ${AUTH_JWT_PUBLIC_KEY_PEM}

    ports:
      - "${PORT:-8081}:${PORT:-8081}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=microservice-network"
      - "traefik.http.routers.user-service.rule=PathPrefix(`/api/users`)"
      - "traefik.http.routers.user-service.entrypoints=web"
      - "traefik.http.services.user-service.loadbalancer.server.port=${PORT:-8081}"
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    external: true
