services:
  tenant-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenant-service
    restart: always
    environment:
      DB_HOST: broker-postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tenant_manager_db
      RABBITMQ_URL: amqp://guest:guest@broker-rabbitmq:5672/
      PORT: "8082"
    ports:
      - "${PORT:-8082}:${PORT:-8082}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=broker-network"
      - "traefik.http.routers.tenant-service.rule=PathPrefix(`/api/register`)"
      - "traefik.http.routers.tenant-service.entrypoints=web"
      - "traefik.http.services.tenant-service.loadbalancer.server.port=${PORT:-8082}"
    networks:
      - broker-network

networks:
  broker-network:
    external: true
