services:
  tenant-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenant-service
    restart: always
    environment:
      PORT: ${PORT:-8082}
      DB_HOST: ${TENANT_DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-tenant_manager_db}
      INTERNAL_SERVICE_TOKEN: ${INTERNAL_SERVICE_TOKEN:-default_internal_service_token}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672/}
      AUTH_JWT_PUBLIC_KEY_PEM: ${AUTH_JWT_PUBLIC_KEY_PEM}

    ports:
      - "${PORT:-8082}:${PORT:-8082}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=microservice-network"
      - "traefik.http.routers.tenant-service.rule=PathPrefix(`/api/tenants`)"
      - "traefik.http.routers.tenant-service.entrypoints=web"
      - "traefik.http.services.tenant-service.loadbalancer.server.port=${PORT:-8082}"
    networks:
      - microservice-network

networks:
  microservice-network:
    name: microservice-network
    external: true
